name: PR Verify

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  testProjectDirectory: src/GitHubActionsDotNet.Api.Tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: dotnet format
      working-directory: ${{ env.testProjectDirectory }}
      run: dotnet format --verbosity detailed --verify-no-changes
    
    - name: dotnet test
      working-directory: ${{ env.testProjectDirectory }}
      run: dotnet test --configuration Release
