name: PR Verify

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: print default dotnet version
      run: dotnet --version

    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.100'

    - name: dotnet test
      working-directory: src/GitHubActionsDotNet.Api.Tests
      run: dotnet test
